services:
  - type: web
    name: my-vite-app
    env: static
    buildCommand: yarn build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html
